// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCedYbtr6dtLEzNVLxl68xbmonk_lj7SK4',
    appId: '1:974952417818:web:5d52b97db23e4941851fa3',
    messagingSenderId: '974952417818',
    projectId: 'supaclock-iee2463',
    authDomain: 'supaclock-iee2463.firebaseapp.com',
    storageBucket: 'supaclock-iee2463.firebasestorage.app',
    measurementId: 'G-KEF5RLYE19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQowcXUrSyf9YGgoNdgLRvSxgLBgzxVvw',
    appId: '1:974952417818:android:8a630c1740d010f4851fa3',
    messagingSenderId: '974952417818',
    projectId: 'supaclock-iee2463',
    storageBucket: 'supaclock-iee2463.firebasestorage.app',
  );
}
