; Extra environment configuration para el test de ECG en ESP32-C3 SuperMini.
;
; NO requieré modificar platformio.ini. Puedes ejecutar el build y el monitor indicando
; este archivo de configuración mediante:
;   pio run -c extra_env_c3_ecg.ini -e test_ecg_c3 -t upload
;   pio device monitor -c extra_env_c3_ecg.ini -e test_ecg_c3
;
; IMPORTANTE:
; Conexiones recomendadas en ESP32-C3 SuperMini:
;   * AD8232 OUTPUT -> GPIO0
;   * AD8232 SDN -> 3.3V (VCC)

[env:test_ecg_c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
build_type = debug
board_build.esp_idf.sdkconfig_defaults = sdkconfig.defaults.c3
board_build.partitions = partitions_c3.csv
board_build.filesystem = spiffs
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
lib_deps = ble_telemetry, ad8232_driver
lib_ignore = ui_fonts, ui_theme, gpio_buttons, power_modes, st7789_driver, JPEGDEC, step_algorithm, max17048_driver, max30102_driver, bmi160_driver, max30205_driver, app_state, supaclock_app, supaclock_ui, har_cnn1d
build_flags =
	-I include
	-D SUPACLOCK_BOARD_C3=1
	-D ENV_TEST_ECG_C3=1
	-Wno-shift-count-negative
	-Wno-overflow
