; PlatformIO Project Configuration File

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
build_type = debug
board_build.esp_idf.sdkconfig_defaults = sdkconfig.defaults
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
lib_deps = i2c_bus, max30205_driver, bmi160_driver, max30102_driver, st7789_driver, JPEGDEC, lvgl/lvgl@~8.4.0, step_algorithm, max17048_driver, ble_telemetry, ad8232_driver, gpio_buttons
build_flags = 
	-I include
	-D LV_CONF_INCLUDE_SIMPLE=1


[env:main_app]
build_flags = ${env.build_flags} -D ENV_MAIN_APP=1

[env:test_general]
build_flags = ${env.build_flags} -D ENV_TEST_GENERAL=1

[env:test_temp]
build_flags = ${env.build_flags} -D ENV_TEST_TEMP=1

[env:test_imu]
build_flags = ${env.build_flags} -D ENV_TEST_IMU=1

[env:test_spo2]
build_flags = ${env.build_flags} -D ENV_TEST_SPO2=1

[env:test_ecg]
build_flags = ${env.build_flags} -D ENV_TEST_ECG=1

[env:test_display]
build_flags = ${env.build_flags} -D ENV_TEST_DISPLAY=1

[env:test_ble]
build_flags = ${env.build_flags} -D ENV_TEST_BLE=1

[env:test_gui]
build_flags = ${env.build_flags} -D ENV_TEST_GUI=1

[env:test_fuel_gauge]
build_flags = ${env.build_flags} -D ENV_TEST_FUEL_GAUGE=1
