; PlatformIO Project Configuration File

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
build_type = debug
board_build.esp_idf.sdkconfig_defaults = sdkconfig.defaults
lib_deps = i2c_bus, max30205_driver, bmi160_driver, max30102_driver, st7789_driver
; ESP-IDF requiere usar macros (Flags) para aislar las rutinas app_main de cada test

[env:main_app]
build_flags = -D ENV_MAIN_APP=1

[env:test_temp]
build_flags = -D ENV_TEST_TEMP=1

[env:test_imu]
build_flags = -D ENV_TEST_IMU=1

[env:test_spo2]
build_flags = -D ENV_TEST_SPO2=1

[env:test_ecg]
build_flags = -D ENV_TEST_ECG=1

[env:test_display]
build_flags = -D ENV_TEST_DISPLAY=1

[env:test_ble]
build_flags = -D ENV_TEST_BLE=1
