idf_component_register(SRCS "ui_font_hero_56.c"
                            "ui_font_subhero_36.c"
                            "ui_font_value_28.c"
                            "ui_font_label_16.c"
                            "ui_font_icon_56.c"
                       INCLUDE_DIRS "."
                       REQUIRES lvgl)
