[platformio]
default_envs = emulator

[env:emulator]
platform = native
build_flags =
    -I include
    -D LV_CONF_INCLUDE_SIMPLE=1
    -D LV_LVGL_H_INCLUDE_SIMPLE=1
    !sdl2-config --cflags --libs
    -lSDL2
lib_deps =
    lvgl/lvgl@~8.4.0
    lvgl/lv_drivers@~8.3.0
